import { createContext, useContext, useState, ReactNode, useCallback } from "react";

export type Language = "zh" | "en" | "ar" | "ja" | "ko" | "fr" | "es" | "de" | "ru" | "pt";

interface LanguageContextType {
  lang: Language;
  setLang: (l: Language) => void;
  t: (key: string) => string;
  dir: "ltr" | "rtl";
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const LANGUAGES: { key: Language; label: string; flag: string }[] = [
  { key: "zh", label: "中文", flag: "🇨🇳" },
  { key: "en", label: "English", flag: "🇺🇸" },
  { key: "ar", label: "العربية", flag: "🇸🇦" },
  { key: "ja", label: "日本語", flag: "🇯🇵" },
  { key: "ko", label: "한국어", flag: "🇰🇷" },
  { key: "fr", label: "Français", flag: "🇫🇷" },
  { key: "es", label: "Español", flag: "🇪🇸" },
  { key: "de", label: "Deutsch", flag: "🇩🇪" },
  { key: "ru", label: "Русский", flag: "🇷🇺" },
  { key: "pt", label: "Português", flag: "🇧🇷" },
];

const translations: Record<Language, Record<string, string>> = {
  zh: {
    "app.name": "罗盘 · Life OS",
    "app.tagline": "你的私人生命导师",
    "auth.email": "邮箱",
    "auth.phone": "手机",
    "auth.email.placeholder": "邮箱地址",
    "auth.password.placeholder": "密码（至少6位）",
    "auth.login": "登录",
    "auth.signup": "注册",
    "auth.no_account": "没有账号？注册",
    "auth.has_account": "已有账号？登录",
    "auth.forgot": "忘记密码？",
    "auth.back": "返回登录",
    "auth.forgot.desc": "输入注册邮箱，我们将发送重置链接",
    "auth.forgot.send": "发送重置链接",
    "auth.forgot.sent": "重置邮件已发送",
    "auth.forgot.check": "请检查收件箱",
    "auth.phone.placeholder": "手机号（含国际区号）",
    "auth.phone.hint": "请输入完整号码，如 +8613812345678",
    "auth.phone.send_otp": "发送验证码",
    "auth.phone.otp_sent": "验证码已发送至",
    "auth.phone.otp_placeholder": "输入6位验证码",
    "auth.phone.verify": "验证并登录",
    "auth.phone.resend": "重新发送",
    "auth.error.default": "操作失败",
    "auth.error.send_fail": "发送失败",
    "auth.error.otp_fail": "发送验证码失败",
    "auth.error.verify_fail": "验证失败",
    "settings.language": "语言",
    // TabBar
    "tab.today": "今日",
    "tab.todo": "待办",
    "tab.wealth": "财富",
    "tab.history": "历史",
    "tab.guide": "指南",
    // Settings
    "settings.theme": "主题设置",
    "settings.mode": "显示模式",
    "settings.mode.dark": "深色",
    "settings.mode.light": "浅色",
    "settings.accent": "主题色",
    "settings.account": "账号管理",
    "settings.logout": "退出登录",
    "settings.export": "导出数据",
  },
  en: {
    "app.name": "Compass · Life OS",
    "app.tagline": "Your Personal Life Mentor",
    "auth.email": "Email",
    "auth.phone": "Phone",
    "auth.email.placeholder": "Email address",
    "auth.password.placeholder": "Password (min 6 chars)",
    "auth.login": "Sign In",
    "auth.signup": "Sign Up",
    "auth.no_account": "No account? Sign up",
    "auth.has_account": "Have an account? Sign in",
    "auth.forgot": "Forgot password?",
    "auth.back": "Back to login",
    "auth.forgot.desc": "Enter your email and we'll send a reset link",
    "auth.forgot.send": "Send Reset Link",
    "auth.forgot.sent": "Reset email sent",
    "auth.forgot.check": "Please check your inbox",
    "auth.phone.placeholder": "Phone number (with country code)",
    "auth.phone.hint": "Enter full number, e.g. +14155551234",
    "auth.phone.send_otp": "Send Code",
    "auth.phone.otp_sent": "Code sent to",
    "auth.phone.otp_placeholder": "Enter 6-digit code",
    "auth.phone.verify": "Verify & Sign In",
    "auth.phone.resend": "Resend",
    "auth.error.default": "Operation failed",
    "auth.error.send_fail": "Failed to send",
    "auth.error.otp_fail": "Failed to send code",
    "auth.error.verify_fail": "Verification failed",
    "settings.language": "Language",
    "tab.today": "Today",
    "tab.todo": "Todos",
    "tab.wealth": "Wealth",
    "tab.history": "History",
    "tab.guide": "Guide",
    "settings.theme": "Theme Settings",
    "settings.mode": "Display Mode",
    "settings.mode.dark": "Dark",
    "settings.mode.light": "Light",
    "settings.accent": "Accent Color",
    "settings.account": "Account",
    "settings.logout": "Sign Out",
    "settings.export": "Export Data",
  },
  ar: {
    "app.name": "البوصلة · Life OS",
    "app.tagline": "مرشدك الشخصي في الحياة",
    "auth.email": "البريد",
    "auth.phone": "الهاتف",
    "auth.email.placeholder": "عنوان البريد الإلكتروني",
    "auth.password.placeholder": "كلمة المرور (٦ أحرف على الأقل)",
    "auth.login": "تسجيل الدخول",
    "auth.signup": "إنشاء حساب",
    "auth.no_account": "ليس لديك حساب؟ سجّل",
    "auth.has_account": "لديك حساب؟ سجّل الدخول",
    "auth.forgot": "نسيت كلمة المرور؟",
    "auth.back": "العودة لتسجيل الدخول",
    "auth.forgot.desc": "أدخل بريدك وسنرسل رابط إعادة التعيين",
    "auth.forgot.send": "إرسال رابط إعادة التعيين",
    "auth.forgot.sent": "تم إرسال بريد إعادة التعيين",
    "auth.forgot.check": "يرجى التحقق من صندوق الوارد",
    "auth.phone.placeholder": "رقم الهاتف (مع رمز الدولة)",
    "auth.phone.hint": "أدخل الرقم الكامل، مثل 966512345678+",
    "auth.phone.send_otp": "إرسال الرمز",
    "auth.phone.otp_sent": "تم إرسال الرمز إلى",
    "auth.phone.otp_placeholder": "أدخل الرمز المكون من ٦ أرقام",
    "auth.phone.verify": "تحقق وسجّل الدخول",
    "auth.phone.resend": "إعادة الإرسال",
    "auth.error.default": "فشلت العملية",
    "auth.error.send_fail": "فشل الإرسال",
    "auth.error.otp_fail": "فشل إرسال الرمز",
    "auth.error.verify_fail": "فشل التحقق",
    "settings.language": "اللغة",
    "tab.today": "اليوم",
    "tab.todo": "المهام",
    "tab.wealth": "الثروة",
    "tab.history": "السجل",
    "tab.guide": "الدليل",
    "settings.theme": "إعدادات المظهر",
    "settings.mode": "وضع العرض",
    "settings.mode.dark": "داكن",
    "settings.mode.light": "فاتح",
    "settings.accent": "لون التمييز",
    "settings.account": "الحساب",
    "settings.logout": "تسجيل الخروج",
    "settings.export": "تصدير البيانات",
  },
  ja: {
    "app.name": "羅針盤 · Life OS",
    "app.tagline": "あなたのライフメンター",
    "auth.email": "メール",
    "auth.phone": "電話",
    "auth.email.placeholder": "メールアドレス",
    "auth.password.placeholder": "パスワード（6文字以上）",
    "auth.login": "ログイン",
    "auth.signup": "新規登録",
    "auth.no_account": "アカウントがない？登録",
    "auth.has_account": "アカウントをお持ち？ログイン",
    "auth.forgot": "パスワードを忘れた？",
    "auth.back": "ログインに戻る",
    "auth.forgot.desc": "メールアドレスを入力すると、リセットリンクを送信します",
    "auth.forgot.send": "リセットリンクを送信",
    "auth.forgot.sent": "リセットメールを送信しました",
    "auth.forgot.check": "受信トレイを確認してください",
    "auth.phone.placeholder": "電話番号（国番号付き）",
    "auth.phone.hint": "完全な番号を入力、例: +819012345678",
    "auth.phone.send_otp": "認証コードを送信",
    "auth.phone.otp_sent": "認証コード送信先:",
    "auth.phone.otp_placeholder": "6桁のコードを入力",
    "auth.phone.verify": "認証してログイン",
    "auth.phone.resend": "再送信",
    "auth.error.default": "操作に失敗しました",
    "auth.error.send_fail": "送信に失敗しました",
    "auth.error.otp_fail": "コード送信に失敗しました",
    "auth.error.verify_fail": "認証に失敗しました",
    "settings.language": "言語",
    "tab.today": "今日",
    "tab.todo": "タスク",
    "tab.wealth": "資産",
    "tab.history": "履歴",
    "tab.guide": "ガイド",
    "settings.theme": "テーマ設定",
    "settings.mode": "表示モード",
    "settings.mode.dark": "ダーク",
    "settings.mode.light": "ライト",
    "settings.accent": "アクセントカラー",
    "settings.account": "アカウント",
    "settings.logout": "ログアウト",
    "settings.export": "データ書き出し",
  },
  ko: {
    "app.name": "나침반 · Life OS",
    "app.tagline": "당신의 인생 멘토",
    "auth.email": "이메일",
    "auth.phone": "전화",
    "auth.email.placeholder": "이메일 주소",
    "auth.password.placeholder": "비밀번호 (최소 6자)",
    "auth.login": "로그인",
    "auth.signup": "회원가입",
    "auth.no_account": "계정이 없나요? 가입",
    "auth.has_account": "계정이 있나요? 로그인",
    "auth.forgot": "비밀번호를 잊으셨나요?",
    "auth.back": "로그인으로 돌아가기",
    "auth.forgot.desc": "이메일을 입력하면 재설정 링크를 보내드립니다",
    "auth.forgot.send": "재설정 링크 보내기",
    "auth.forgot.sent": "재설정 이메일이 전송되었습니다",
    "auth.forgot.check": "받은 편지함을 확인하세요",
    "auth.phone.placeholder": "전화번호 (국가 코드 포함)",
    "auth.phone.hint": "전체 번호 입력, 예: +821012345678",
    "auth.phone.send_otp": "인증번호 보내기",
    "auth.phone.otp_sent": "인증번호 전송:",
    "auth.phone.otp_placeholder": "6자리 코드 입력",
    "auth.phone.verify": "인증 후 로그인",
    "auth.phone.resend": "재전송",
    "auth.error.default": "작업 실패",
    "auth.error.send_fail": "전송 실패",
    "auth.error.otp_fail": "코드 전송 실패",
    "auth.error.verify_fail": "인증 실패",
    "settings.language": "언어",
    "tab.today": "오늘",
    "tab.todo": "할 일",
    "tab.wealth": "자산",
    "tab.history": "기록",
    "tab.guide": "가이드",
    "settings.theme": "테마 설정",
    "settings.mode": "표시 모드",
    "settings.mode.dark": "다크",
    "settings.mode.light": "라이트",
    "settings.accent": "강조 색상",
    "settings.account": "계정",
    "settings.logout": "로그아웃",
    "settings.export": "데이터 내보내기",
  },
  fr: {
    "app.name": "Boussole · Life OS",
    "app.tagline": "Votre mentor de vie personnel",
    "auth.email": "Email",
    "auth.phone": "Téléphone",
    "auth.email.placeholder": "Adresse email",
    "auth.password.placeholder": "Mot de passe (min 6 car.)",
    "auth.login": "Connexion",
    "auth.signup": "Inscription",
    "auth.no_account": "Pas de compte ? Inscrivez-vous",
    "auth.has_account": "Déjà un compte ? Connectez-vous",
    "auth.forgot": "Mot de passe oublié ?",
    "auth.back": "Retour à la connexion",
    "auth.forgot.desc": "Entrez votre email pour recevoir un lien de réinitialisation",
    "auth.forgot.send": "Envoyer le lien",
    "auth.forgot.sent": "Email de réinitialisation envoyé",
    "auth.forgot.check": "Vérifiez votre boîte de réception",
    "auth.phone.placeholder": "Numéro (avec indicatif)",
    "auth.phone.hint": "Numéro complet, ex: +33612345678",
    "auth.phone.send_otp": "Envoyer le code",
    "auth.phone.otp_sent": "Code envoyé à",
    "auth.phone.otp_placeholder": "Code à 6 chiffres",
    "auth.phone.verify": "Vérifier et se connecter",
    "auth.phone.resend": "Renvoyer",
    "auth.error.default": "Échec de l'opération",
    "auth.error.send_fail": "Échec de l'envoi",
    "auth.error.otp_fail": "Échec de l'envoi du code",
    "auth.error.verify_fail": "Échec de la vérification",
    "settings.language": "Langue",
    "tab.today": "Aujourd'hui",
    "tab.todo": "Tâches",
    "tab.wealth": "Finance",
    "tab.history": "Historique",
    "tab.guide": "Guide",
    "settings.theme": "Paramètres du thème",
    "settings.mode": "Mode d'affichage",
    "settings.mode.dark": "Sombre",
    "settings.mode.light": "Clair",
    "settings.accent": "Couleur d'accent",
    "settings.account": "Compte",
    "settings.logout": "Déconnexion",
    "settings.export": "Exporter les données",
  },
  es: {
    "app.name": "Brújula · Life OS",
    "app.tagline": "Tu mentor de vida personal",
    "auth.email": "Email",
    "auth.phone": "Teléfono",
    "auth.email.placeholder": "Correo electrónico",
    "auth.password.placeholder": "Contraseña (mín 6 car.)",
    "auth.login": "Iniciar sesión",
    "auth.signup": "Registrarse",
    "auth.no_account": "¿Sin cuenta? Regístrate",
    "auth.has_account": "¿Tienes cuenta? Inicia sesión",
    "auth.forgot": "¿Olvidaste la contraseña?",
    "auth.back": "Volver al login",
    "auth.forgot.desc": "Ingresa tu email y enviaremos un enlace de restablecimiento",
    "auth.forgot.send": "Enviar enlace",
    "auth.forgot.sent": "Email de restablecimiento enviado",
    "auth.forgot.check": "Revisa tu bandeja de entrada",
    "auth.phone.placeholder": "Número (con código de país)",
    "auth.phone.hint": "Número completo, ej: +34612345678",
    "auth.phone.send_otp": "Enviar código",
    "auth.phone.otp_sent": "Código enviado a",
    "auth.phone.otp_placeholder": "Código de 6 dígitos",
    "auth.phone.verify": "Verificar e iniciar sesión",
    "auth.phone.resend": "Reenviar",
    "auth.error.default": "Error en la operación",
    "auth.error.send_fail": "Error al enviar",
    "auth.error.otp_fail": "Error al enviar código",
    "auth.error.verify_fail": "Error de verificación",
    "settings.language": "Idioma",
    "tab.today": "Hoy",
    "tab.todo": "Tareas",
    "tab.wealth": "Finanzas",
    "tab.history": "Historial",
    "tab.guide": "Guía",
    "settings.theme": "Configuración de tema",
    "settings.mode": "Modo de pantalla",
    "settings.mode.dark": "Oscuro",
    "settings.mode.light": "Claro",
    "settings.accent": "Color de acento",
    "settings.account": "Cuenta",
    "settings.logout": "Cerrar sesión",
    "settings.export": "Exportar datos",
  },
  de: {
    "app.name": "Kompass · Life OS",
    "app.tagline": "Dein persönlicher Lebensmentor",
    "auth.email": "E-Mail",
    "auth.phone": "Telefon",
    "auth.email.placeholder": "E-Mail-Adresse",
    "auth.password.placeholder": "Passwort (mind. 6 Zeichen)",
    "auth.login": "Anmelden",
    "auth.signup": "Registrieren",
    "auth.no_account": "Kein Konto? Registrieren",
    "auth.has_account": "Konto vorhanden? Anmelden",
    "auth.forgot": "Passwort vergessen?",
    "auth.back": "Zurück zum Login",
    "auth.forgot.desc": "E-Mail eingeben für den Zurücksetzungslink",
    "auth.forgot.send": "Link senden",
    "auth.forgot.sent": "Zurücksetzungs-E-Mail gesendet",
    "auth.forgot.check": "Bitte Posteingang prüfen",
    "auth.phone.placeholder": "Telefonnummer (mit Landesvorwahl)",
    "auth.phone.hint": "Vollständige Nummer, z.B. +4915112345678",
    "auth.phone.send_otp": "Code senden",
    "auth.phone.otp_sent": "Code gesendet an",
    "auth.phone.otp_placeholder": "6-stelligen Code eingeben",
    "auth.phone.verify": "Verifizieren & anmelden",
    "auth.phone.resend": "Erneut senden",
    "auth.error.default": "Vorgang fehlgeschlagen",
    "auth.error.send_fail": "Senden fehlgeschlagen",
    "auth.error.otp_fail": "Code senden fehlgeschlagen",
    "auth.error.verify_fail": "Verifizierung fehlgeschlagen",
    "settings.language": "Sprache",
    "tab.today": "Heute",
    "tab.todo": "Aufgaben",
    "tab.wealth": "Finanzen",
    "tab.history": "Verlauf",
    "tab.guide": "Anleitung",
    "settings.theme": "Thema-Einstellungen",
    "settings.mode": "Anzeigemodus",
    "settings.mode.dark": "Dunkel",
    "settings.mode.light": "Hell",
    "settings.accent": "Akzentfarbe",
    "settings.account": "Konto",
    "settings.logout": "Abmelden",
    "settings.export": "Daten exportieren",
  },
  ru: {
    "app.name": "Компас · Life OS",
    "app.tagline": "Ваш личный наставник",
    "auth.email": "Email",
    "auth.phone": "Телефон",
    "auth.email.placeholder": "Электронная почта",
    "auth.password.placeholder": "Пароль (мин. 6 символов)",
    "auth.login": "Войти",
    "auth.signup": "Регистрация",
    "auth.no_account": "Нет аккаунта? Зарегистрируйтесь",
    "auth.has_account": "Есть аккаунт? Войдите",
    "auth.forgot": "Забыли пароль?",
    "auth.back": "Назад к входу",
    "auth.forgot.desc": "Введите email для получения ссылки сброса",
    "auth.forgot.send": "Отправить ссылку",
    "auth.forgot.sent": "Письмо для сброса отправлено",
    "auth.forgot.check": "Проверьте входящие",
    "auth.phone.placeholder": "Номер (с кодом страны)",
    "auth.phone.hint": "Полный номер, напр. +79161234567",
    "auth.phone.send_otp": "Отправить код",
    "auth.phone.otp_sent": "Код отправлен на",
    "auth.phone.otp_placeholder": "Введите 6-значный код",
    "auth.phone.verify": "Подтвердить и войти",
    "auth.phone.resend": "Отправить повторно",
    "auth.error.default": "Ошибка операции",
    "auth.error.send_fail": "Ошибка отправки",
    "auth.error.otp_fail": "Ошибка отправки кода",
    "auth.error.verify_fail": "Ошибка проверки",
    "settings.language": "Язык",
    "tab.today": "Сегодня",
    "tab.todo": "Задачи",
    "tab.wealth": "Финансы",
    "tab.history": "История",
    "tab.guide": "Гид",
    "settings.theme": "Настройки темы",
    "settings.mode": "Режим отображения",
    "settings.mode.dark": "Тёмный",
    "settings.mode.light": "Светлый",
    "settings.accent": "Цвет акцента",
    "settings.account": "Аккаунт",
    "settings.logout": "Выйти",
    "settings.export": "Экспорт данных",
  },
  pt: {
    "app.name": "Bússola · Life OS",
    "app.tagline": "Seu mentor de vida pessoal",
    "auth.email": "Email",
    "auth.phone": "Telefone",
    "auth.email.placeholder": "Endereço de email",
    "auth.password.placeholder": "Senha (mín 6 caracteres)",
    "auth.login": "Entrar",
    "auth.signup": "Cadastrar",
    "auth.no_account": "Sem conta? Cadastre-se",
    "auth.has_account": "Já tem conta? Entre",
    "auth.forgot": "Esqueceu a senha?",
    "auth.back": "Voltar ao login",
    "auth.forgot.desc": "Digite seu email para receber o link de redefinição",
    "auth.forgot.send": "Enviar link",
    "auth.forgot.sent": "Email de redefinição enviado",
    "auth.forgot.check": "Verifique sua caixa de entrada",
    "auth.phone.placeholder": "Número (com código do país)",
    "auth.phone.hint": "Número completo, ex: +5511912345678",
    "auth.phone.send_otp": "Enviar código",
    "auth.phone.otp_sent": "Código enviado para",
    "auth.phone.otp_placeholder": "Código de 6 dígitos",
    "auth.phone.verify": "Verificar e entrar",
    "auth.phone.resend": "Reenviar",
    "auth.error.default": "Falha na operação",
    "auth.error.send_fail": "Falha no envio",
    "auth.error.otp_fail": "Falha ao enviar código",
    "auth.error.verify_fail": "Falha na verificação",
    "settings.language": "Idioma",
    "tab.today": "Hoje",
    "tab.todo": "Tarefas",
    "tab.wealth": "Finanças",
    "tab.history": "Histórico",
    "tab.guide": "Guia",
    "settings.theme": "Configurações de tema",
    "settings.mode": "Modo de exibição",
    "settings.mode.dark": "Escuro",
    "settings.mode.light": "Claro",
    "settings.accent": "Cor de destaque",
    "settings.account": "Conta",
    "settings.logout": "Sair",
    "settings.export": "Exportar dados",
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [lang, setLangState] = useState<Language>(() =>
    (localStorage.getItem("los-lang") as Language) || "zh"
  );

  const setLang = useCallback((l: Language) => {
    setLangState(l);
    localStorage.setItem("los-lang", l);
    document.documentElement.dir = l === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = l;
  }, []);

  const t = useCallback((key: string): string => {
    return translations[lang]?.[key] || translations.zh[key] || key;
  }, [lang]);

  const dir = lang === "ar" ? "rtl" : "ltr";

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, dir }}>
      {children}
    </LanguageContext.Provider>
  );
}

// eslint-disable-next-line react-refresh/only-export-components
export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
}
